# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='DUMMY', max_length=100),
            preserve_default=False,
        ),
    ]
